title: Andrew Bergey
description: Research in underwater acoustics, sensing, and communication
remote_theme: alshedivat/al-folio
markdown: kramdown

keywords: underwater acoustic, metastructure, research 
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: ðŸ”‰
last_updated: true 
back_to_top: true 

navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true

profile:
  align: left
  image: headshot.jpg
  image_circular: false

social:
  - icon: linkedin
    link: https://www.linkedin.com/in/andrew-bergey/
  - icon: google-scholar
    link: https://scholar.google.com/citations?user=7PUB3g4AAAAJ&hl=en&oi=ao
  - icon: github
    link: https://github.com/adbergey
  - icon: envelope
    link: mailto:adbergey@uw.edu

navbar:
  - title: About
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
